# Generated by Django 3.0.5 on 2020-07-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='name'),
            preserve_default=False,
        ),
    ]
