# Generated by Django 3.0.5 on 2020-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyshop', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 's'), ('sportswear', 'sw'), ('outwear', 'ow')], max_length=10),
        ),
    ]
