# Generated by Django 3.0.5 on 2020-07-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyshop', '0003_auto_20200725_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirt', 'shirt'), ('sportswear', 'sportswear'), ('outwear', 'outwear')], max_length=10),
        ),
    ]
